In [1]:
from PySigmoid import *
import numpy as np
import matplotlib.pyplot as plt

In [2]:
set_posit_env(8,0)

In [3]:
def posify(x):
    if type(x) == np.ndarray:
        if len(x.shape) == 1:
            return np.array([Posit(y) for y in x])
        else:
            return np.array([[Posit(z) for z in y] for y in x])
    else:
        return Posit(x)

In [109]:
from functools import reduce
import operator

# @staticmethod
def fused_sum(a):
    if all(isinstance(x, Posit) for x in a):
        r = reduce(operator.add, map(lambda x: Quire(x), a))
        return Posit(r)
    else:
        raise Exception("Argument must be a list of posit")

# @staticmethod
def fused_dot_product(a, b):
    if all(isinstance(x, Posit) for x in (a + b)):
        r = reduce(operator.add, map(lambda x, y: Quire(x) * Quire(y), a,b))
        return Posit(r)
    else:
        raise Exception("Arguments must be lists of posit")
        
def dot_product(a, b):
    if all(isinstance(x, Posit) for x in (a + b)):
        r = reduce(operator.add, map(lambda x, y: x * y, a,b))
        return r
    else:
        raise Exception("Arguments must be lists of posit")
        
def fused_matmult(a, b):
    zip_b = zip(*b)
    # uncomment next line if python 3 :
    zip_b = list(zip_b)
    return [[fused_dot_product(row_a, col_b) 
             for col_b in zip_b] for row_a in a]

def matmult(a, b):
    zip_b = zip(*b)
    # uncomment next line if python 3 :
    zip_b = list(zip_b)
    return [[dot_product(row_a, col_b) 
             for col_b in zip_b] for row_a in a]

In [46]:
# Example showing Fused operations

# check that all the operands and the result
# are in the environment, but not the mid-result.
# for i in range (32):
#     print(Posit(i))

a = Posit(10)
b = Posit(2)
c = Posit(4)
# Fused Multiply-Add
print('Fused Multiply-Add: {}  Multiply-Add: {}'.format(Posit(Quire(c) + Quire(a) * Quire(b)), c + a * b))

# Fused Multiply-Sub
print('Fused Multiply-Sub: {}  Multiply-Sub: {}'.format(Posit(Quire(a) * Quire(b) - Quire(c)), a * b - c))

Fused Multiply-Add: 24  Multiply-Add: 16
Fused Multiply-Sub: 16  Multiply-Sub: 12


In [47]:
tenthousand = range(10000)

q = []
result = Quire(0)
for i in tenthousand:
    q.append(Quire(i))
    result += Quire(i)
print(sum(tenthousand))
print(result)
print(Posit(result))


49995000
49995000
64


In [43]:
# Fused dot product example
a = np.array([1, 2, 3])
b = np.array([4, -5, 6])
print(a.dot(b))
print(fused_dot_product(posify(a), posify(b)))
print(dot_product(posify(a), posify(b)))

12
12
10


In [115]:
# Matrix multiplication
A = np.array([[-1, -2, 2],[4 , 6 , -3]])
B = np.array([[1, 5 , 2 , -4],[-2 , 6 , -3 , 3],[-1 , 7 , 0 , 4]])
print('Correct result:')
print(A.dot(B)) # same as A @ B

print('Posit Matrix multiplication result:')
print(np.array(matmult(posify(A), posify(B))))
print('Fused Matrix multiplication result:')
print(np.array(fused_matmult(posify(A), posify(B))))

Correct result:
[[  1  -3   4   6]
 [ -5  35 -10 -10]]
Posit Matrix multiplication result:
[[1 -2 4 6]
 [-5 8 -8 -12]]
Fused Matrix multiplication result:
[[1 -3 4 6]
 [-5 32 -10 -10]]
